server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Demo?characterEncoding=utf8&useSSL=false&max_allowed_packet=64M
    username: root
    password: '@disyroot'

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.daisy.demo.entity

logging:
  level:
    com.daisy.demo.dao: debug


